---

- hosts: all
  module_defaults:
    ansible.builtin.file:
       pip: pip3
       python: python3
  become: true
  tasks:

    - name: Installation of python3 & pip3 package For ubuntu
      apt:
        name:
          - python3
          - pip
      when: ansible_distribution == "Ubuntu"

    - name: Installation of python3 & pip3 package for CentOS
      dnf:
        name:
           - python3
           - python3-pip
        state: latest
        update_cache: yes
      when: ansible_distribution == "CentOS"

    - name: installation of java for Ubuntu
      apt:
        name: "{{packages}}"
      when: ansible_distribution == "Ubuntu"
      vars:
       packages:
        - openjdk-1.8.0-jdk

